language: android
sudo: false
jdk: oraclejdk8

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses
  - yes | sdkmanager "tools" &>/dev/null
  - yes | sdkmanager "platform-tools" &>/dev/null
  - yes | sdkmanager "platforms;android-28" &>/dev/null
# Download emulator
  - yes | sdkmanager "platforms;android-24" &>/dev/null
  - yes | sdkmanager "system-images;android-24;default;x86_64" &>/dev/null
# Update remaining dependencies and accept licenses
  - yes | sdkmanager --update &>/dev/null
  - yes | sdkmanager --licenses &>/dev/null
  - echo yes | android update sdk --all --filter build-tools-28.0.3 --no-ui --force
# Setup emulator
  - echo "no" | avdmanager create avd -n test -k "system-images;android-24;default;x86_64" -c 200M -f &>/dev/null
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-accel -no-snapshot -no-window -camera-back none -camera-front none & &>/dev/null

env:
  global:
  - ANDROID_API=28
  - EMULATOR_API=24
  - ANDROID_BUILD_TOOLS=28.0.3
  - ADB_INSTALL_TIMEOUT=8 # minutes

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - sys-img-armeabi-v7a-android-$ANDROID_API
  - extra-google-m2repository

before_script:
- echo no | android create avd --force -n test -t android-28
  --abi armeabi-v7a emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell settings put global window_animation_scale 0 &
- adb shell settings put global transition_animation_scale 0 &
- adb shell settings put global animator_duration_scale 0 &
- adb shell input keyevent 82 &