language: android
sudo: required
jdk: oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-28"
  - mkdir -p "$ANDROID_HOME/licenses"
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - ./gradlew dependencies || true

env:
  global:
  - ANDROID_API=28
  - EMULATOR_API=24
  - ANDROID_BUILD_TOOLS=26.1.1
  - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository
