language: android
sudo: required
jdk: oraclejdk8

env:
  global:
  - ANDROID_API=28
  - EMULATOR_API=24
  - ANDROID_BUILD_TOOLS=26.1.1
  - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository

before_install:
    - yes | sdkmanager "platforms;android-28"
