language: android
sudo: false
jdk: oraclejdk8

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses

env:
  global:
  - ANDROID_API=28
  - EMULATOR_API=24
  - ANDROID_BUILD_TOOLS=26.1.1
  - ADB_INSTALL_TIMEOUT=8 # minutes

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - sys-img-armeabi-v7a-android-$ANDROID_API
  - extra-google-m2repository
